const LightTheme = {
    mainText : 'text-[#007CBE]',
    normalText: 'text-[#1E1B18]',
    firstShadow: 'shadow-[#1E1B18]',
    secondBg: 'bg-[#FF7F11]',
    thirdBg: 'bg-white',
    hoverText: 'hover:text-[#FF7F11]',
    inputBorder: 'border-[#ff801185]',
    inputPlaceHolder: 'placeholder-[#1E1B18]',
    warningText: 'text-red-500',
    gradient: 'from-[#252422] to-[#007CBE]',
    contactBtext: 'text-white',
    fourthBg: 'bg-[#007CBE]',
    footerBg: 'bg-[#0f1c55]',
    secondText: 'text-[#F1F6F9]',
    buttonHover : 'hover:bg-[#007bbea9]',
    cardFrontText : 'text-[#F9F8F8]',
    socialsBg : '#007CBE',
    secondBorder: 'border-[#007CBE]',
    PostBg : 'bg-[#007bbe07]',
    postShadow: 'shadow-gray-300',
    skillHover: 'hover:bg-[#FF7F11]',
    skillBg: 'bg-[#F9F8F8]',
    sunColor: 'text-orange-300',
    moonColor: 'text-slate-800',
    mainBg: 'bg-[#F1F6F9]',
    techBg: 'bg-[#007bbe1a]',
}

const DarkTheme = {
    mainText : 'dark:text-[#C84B31]',
    normalText: 'dark:text-[#EEEEEE]',
    firstShadow: 'dark:shadow-[#EEEEEE]',
    secondBg: 'dark:bg-[#393E46]',
    thirdBg: 'dark:bg-red-950',
    hoverText: 'dark:hover:text-[#393E46]',
    inputBorder: 'dark:border-[#ff801185]',
    inputPlaceHolder: 'dark:placeholder-[#EEEEEE]',
    warningText: 'dark:text-red-500',
    gradient: 'dark:from-[#252422] dark:to-[#D65A31]',
    contactBtext: 'dark:text-white',
    fourthBg: 'dark:bg-[#D65A31]',
    footerBg: 'dark:bg-[#2D4263]',
    secondText: 'dark:text-[#222831]',
    buttonHover : 'dark:hover:bg-[#007bbea9]',
    cardFrontText : 'dark:text-[#F9F8F8]',
    socialsBg : '#D65A31',
    secondBorder: 'dark:border-[#D65A31]',
    PostBg : 'dark:bg-[#007bbe07]',
    postShadow: 'dark:shadow-gray-300',
    skillHover: 'dark:hover:bg-[#393E46]',
    skillBg: 'dark:bg-[#F9F8F8]',
    sunColor: 'dark:text-orange-300',
    moonColor: 'dark:text-slate-800',
    mainBg: 'dark:bg-[#222831]',
    techBg: 'bg-[#007bbe1a]',
}

export {LightTheme , DarkTheme};